import { BiEditAlt } from "react-icons/bi";

export var tableRows = [
    {classNameTH:'py-3 ', firstnameClassName:'text-blue-600 cursor-pointer font-bold hover:text-[blue]', genderClassName:'text-blue-600 cursor-pointer font-bold hover:text-[blue]', classNameTD:'', title:'1',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith', edit:<BiEditAlt size={22} className='text-blue-700 cursor-pointer hover:text-[blue]'/>},
    {classNameTH:'py-3 ', classNameTD:'', title:'2', firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'3',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'4',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'5',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'6',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'7',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'8',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'9',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'10',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'1',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'2', firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'3',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'4',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'5',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'6',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'7',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'8',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'9',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'10',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'1',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'2', firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'3',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'4',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'5',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'6',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'7',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'8',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'9',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'10',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'1',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'2', firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'3',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'4',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'5',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'6',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'7',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'8',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'9',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'10',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'1',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'2', firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'3',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'4',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'5',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'6',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'7',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'8',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith Mission International World Wide'},
    {classNameTH:'py-3 ', classNameTD:'', title:'9',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
    {classNameTH:'py-3 ', classNameTD:'', title:'10',  firstname:'James', lastname:'Bode', gender:'Male', birthday:'April 12', church:'The Gospel Faith'},
  ];