import { getLinkPostTrans } from "@/lib/apiRequest/urlLinks";
import { dateFmtISO } from "@/lib/date/dateFormats";



export const preparePAQuery =(form, user, personalAcct, existingAcctCodeLen) =>{
  const url = getLinkPostTrans(user.companyId).post;
  const {id, 
    type, 
    title, 
    accountCode,
    firstname, 
    lastname, 
    othernames, 
    dob, 
    email, 
    phoneNo, 
    residentialAddress, 
    formNo, 
    position, 
    occupation,
    nextContactPersonName, 
    nextContactPersonPhoneNo, 
    nextContactPersonEmail, 
    companyName, 
    companyEmail, 
    companyPhoneNo, 
    companyAddress, 
    businessType, 
    region, 
    country, 
    state, 
    zip, 
    info, 
    createdBy, 
    createdAt, 
    updatedBy, } = form;


    let accountCodeNew = personalAcct==="vendors"? "V-"+parseInt(accountCode).toString().padStart(existingAcctCodeLen || 6,0) : "C-"+parseInt(accountCode).toString().padStart(existingAcctCodeLen || 6,0);
    let accountCodePaded = accountCode.toString().includes("V") || accountCode.toString().includes("C")? accountCode : accountCodeNew; 

  let body = {
    act:"INSERT",
    table:user.companyId+"_"+personalAcct,
    fields:[
      `type`, 
      `title`, 
      `accountCode`, 
      `firstname`, 
      `lastname`, 
      `othernames`, 
      `dob`, 
      `email`, 
      `accountGroup`,
      `phoneNo`, 
      `residentialAddress`, 
      `formNo`, 
      `position`, 
      `occupation`, 
      `nextContactPersonName`, 
      `nextContactPersonPhoneNo`, 
      `nextContactPersonEmail`, 
      `companyName`, 
      `companyEmail`, 
      `companyPhoneNo`, 
      `companyAddress`, 
      `businessType`, 
      `region`, 
      `country`, 
      `state`, 
      `zip`,
      `imageLink`,  
      `info`,
      `registeredDate`, 
      `createdBy`, 
      `updatedBy`, 
      `createdAt`, 
      `updatedAt`
    ],
    values :[[
        type, 
        title, 
        accountCodePaded, 
        firstname, 
        lastname, 
        othernames, 
        dob, 
        email,
        form?.accountGroup?.toUpperCase() || "GENERAL", 
        phoneNo, 
        residentialAddress, 
        formNo, 
        position, 
        occupation,
        nextContactPersonName, 
        nextContactPersonPhoneNo, 
        nextContactPersonEmail, 
        companyName, 
        companyEmail, 
        companyPhoneNo, 
        companyAddress, 
        businessType, 
        region, 
        country, 
        state, 
        zip,
        form?.imageLink || null, 
        info, 
        dateFmtISO(), 
        createdBy || user.userId, 
        updatedBy || user.userId,
        createdAt || dateFmtISO(),  
        dateFmtISO()]],
    types:[
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR"
    ]
  };
  return {body, url}
}   

