import { dateFmtISO } from "@/lib/date/dateFormats";
import { getLinkPostTrans } from "@/lib/apiRequest/urlLinks";


export const updatePAQuery =(form, user, personalAcct) =>{
  const url = getLinkPostTrans().patch;
  const {id, 
    type, 
    title, 
    accountCode,
    firstname, 
    lastname, 
    othernames, 
    dob, 
    email, 
    phoneNo, 
    residentialAddress, 
    formNo, 
    position, 
    nextContactPersonName, 
    nextContactPersonPhoneNo, 
    nextContactPersonEmail, 
    companyName, 
    companyEmail, 
    companyPhoneNo, 
    companyAddress, 
    businessType, 
    region, 
    country, 
    state, 
    zip, 
    info, 
    updatedBy, } = form;


    let accountCodeNew = personalAcct==="vendors"? "V-"+parseInt(accountCode).toString().padStart(6,0) : "C-"+parseInt(accountCode).toString().padStart(6,0);
    let accountCodePaded = accountCode.toString().includes("V") || accountCode.toString().includes("C")? accountCode : accountCodeNew; 

  let body = {
    "act":"UPDATE",
      whereField:'id',
      whereValue:id,
      whereType:'INT',
    table:user.companyId+"_"+personalAcct,
    fields:[
      `type`, 
      `title`, 
      `accountCode`, 
      `firstname`, 
      `lastname`, 
      `othernames`, 
      `dob`, 
      `email`, 
      `phoneNo`, 
      `residentialAddress`, 
      `formNo`, 
      `position`, 
      `nextContactPersonName`, 
      `nextContactPersonPhoneNo`, 
      `nextContactPersonEmail`, 
      `companyName`, 
      `companyEmail`, 
      `companyPhoneNo`, 
      `companyAddress`, 
      `businessType`, 
      `region`, 
      `country`, 
      `state`, 
      `zip`,  
      `info`,
      `registeredDate`, 
      `updatedBy`, 
      `updatedAt`
    ],
    values :[
        type, 
        title, 
        accountCodePaded, 
        firstname, 
        lastname, 
        othernames, 
        dob, 
        email, 
        phoneNo, 
        residentialAddress, 
        formNo, 
        position, 
        nextContactPersonName, 
        nextContactPersonPhoneNo, 
        nextContactPersonEmail, 
        companyName, 
        companyEmail, 
        companyPhoneNo, 
        companyAddress, 
        businessType, 
        region, 
        country, 
        state, 
        zip, 
        info, 
        dateFmtISO(), 
        updatedBy || user.userId,
        dateFmtISO()],
    types:[
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR",
      "VARCHAR"
    ]
  };
  return {body, url}
}   

